# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgCollegeError2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgCollegeError2(object):
    def setupUi(self, dlgCollegeError2):
        dlgCollegeError2.setObjectName("dlgCollegeError2")
        dlgCollegeError2.resize(202, 147)
        dlgCollegeError2.setMinimumSize(QtCore.QSize(202, 147))
        dlgCollegeError2.setMaximumSize(QtCore.QSize(202, 147))
        dlgCollegeError2.setStyleSheet("background: #1b2023;")
        self.txtCollegeError2 = QtWidgets.QLabel(dlgCollegeError2)
        self.txtCollegeError2.setGeometry(QtCore.QRect(40, 20, 121, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtCollegeError2.setFont(font)
        self.txtCollegeError2.setStyleSheet("color: #c3bcc2;")
        self.txtCollegeError2.setObjectName("txtCollegeError2")
        self.btnCollegeError2 = QtWidgets.QPushButton(dlgCollegeError2)
        self.btnCollegeError2.setGeometry(QtCore.QRect(60, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnCollegeError2.setFont(font)
        self.btnCollegeError2.setStyleSheet("background: white;\n"
"")
        self.btnCollegeError2.setObjectName("btnCollegeError2")

        self.retranslateUi(dlgCollegeError2)
        QtCore.QMetaObject.connectSlotsByName(dlgCollegeError2)

    def retranslateUi(self, dlgCollegeError2):
        _translate = QtCore.QCoreApplication.translate
        dlgCollegeError2.setWindowTitle(_translate("dlgCollegeError2", "Error"))
        self.txtCollegeError2.setText(_translate("dlgCollegeError2", "  College Code \n"
" already exists"))
        self.btnCollegeError2.setText(_translate("dlgCollegeError2", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgCollegeError2 = QtWidgets.QDialog()
    ui = Ui_dlgCollegeError2()
    ui.setupUi(dlgCollegeError2)
    dlgCollegeError2.show()
    sys.exit(app.exec_())
