# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgCollegeError3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgCollegeError3(object):
    def setupUi(self, dlgCollegeError3):
        dlgCollegeError3.setObjectName("dlgCollegeError3")
        dlgCollegeError3.resize(202, 147)
        dlgCollegeError3.setMinimumSize(QtCore.QSize(202, 147))
        dlgCollegeError3.setMaximumSize(QtCore.QSize(202, 147))
        dlgCollegeError3.setStyleSheet("background: #1b2023;")
        self.txtCollegeError3 = QtWidgets.QLabel(dlgCollegeError3)
        self.txtCollegeError3.setGeometry(QtCore.QRect(40, 20, 121, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtCollegeError3.setFont(font)
        self.txtCollegeError3.setStyleSheet("color: #c3bcc2;")
        self.txtCollegeError3.setObjectName("txtCollegeError3")
        self.btnCollegeError3 = QtWidgets.QPushButton(dlgCollegeError3)
        self.btnCollegeError3.setGeometry(QtCore.QRect(60, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnCollegeError3.setFont(font)
        self.btnCollegeError3.setStyleSheet("background: white;\n"
"")
        self.btnCollegeError3.setObjectName("btnCollegeError3")

        self.retranslateUi(dlgCollegeError3)
        QtCore.QMetaObject.connectSlotsByName(dlgCollegeError3)

    def retranslateUi(self, dlgCollegeError3):
        _translate = QtCore.QCoreApplication.translate
        dlgCollegeError3.setWindowTitle(_translate("dlgCollegeError3", "Error"))
        self.txtCollegeError3.setText(_translate("dlgCollegeError3", "  College Name \n"
" already exists"))
        self.btnCollegeError3.setText(_translate("dlgCollegeError3", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgCollegeError3 = QtWidgets.QDialog()
    ui = Ui_dlgCollegeError3()
    ui.setupUi(dlgCollegeError3)
    dlgCollegeError3.show()
    sys.exit(app.exec_())
