# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgCollegeDeleted.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgCollegeDeleted(object):
    def setupUi(self, dlgCollegeDeleted):
        dlgCollegeDeleted.setObjectName("dlgCollegeDeleted")
        dlgCollegeDeleted.resize(202, 147)
        dlgCollegeDeleted.setMinimumSize(QtCore.QSize(202, 147))
        dlgCollegeDeleted.setMaximumSize(QtCore.QSize(202, 147))
        dlgCollegeDeleted.setStyleSheet("background: #1b2023;\n"
"")
        self.btnDlgCollegeDeleted = QtWidgets.QPushButton(dlgCollegeDeleted)
        self.btnDlgCollegeDeleted.setGeometry(QtCore.QRect(60, 100, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgCollegeDeleted.setFont(font)
        self.btnDlgCollegeDeleted.setStyleSheet("background: white;\n"
"")
        self.btnDlgCollegeDeleted.setObjectName("btnDlgCollegeDeleted")
        self.txtCollegeDeleted = QtWidgets.QLabel(dlgCollegeDeleted)
        self.txtCollegeDeleted.setGeometry(QtCore.QRect(20, 10, 171, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtCollegeDeleted.setFont(font)
        self.txtCollegeDeleted.setStyleSheet("color: #c3bcc2;")
        self.txtCollegeDeleted.setObjectName("txtCollegeDeleted")

        self.retranslateUi(dlgCollegeDeleted)
        QtCore.QMetaObject.connectSlotsByName(dlgCollegeDeleted)

    def retranslateUi(self, dlgCollegeDeleted):
        _translate = QtCore.QCoreApplication.translate
        dlgCollegeDeleted.setWindowTitle(_translate("dlgCollegeDeleted", "College Added"))
        self.btnDlgCollegeDeleted.setText(_translate("dlgCollegeDeleted", "Ok"))
        self.txtCollegeDeleted.setText(_translate("dlgCollegeDeleted", "College Deleted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgCollegeDeleted = QtWidgets.QDialog()
    ui = Ui_dlgCollegeDeleted()
    ui.setupUi(dlgCollegeDeleted)
    dlgCollegeDeleted.show()
    sys.exit(app.exec_())
