# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgCollegeError.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgCollegeError(object):
    def setupUi(self, dlgCollegeError):
        dlgCollegeError.setObjectName("dlgCollegeError")
        dlgCollegeError.resize(202, 147)
        dlgCollegeError.setMinimumSize(QtCore.QSize(202, 147))
        dlgCollegeError.setMaximumSize(QtCore.QSize(202, 147))
        dlgCollegeError.setStyleSheet("background: #1b2023;")
        self.txtCollegeError = QtWidgets.QLabel(dlgCollegeError)
        self.txtCollegeError.setGeometry(QtCore.QRect(40, 20, 131, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtCollegeError.setFont(font)
        self.txtCollegeError.setStyleSheet("color: #c3bcc2;")
        self.txtCollegeError.setObjectName("txtCollegeError")
        self.btnDlgCollegeError = QtWidgets.QPushButton(dlgCollegeError)
        self.btnDlgCollegeError.setGeometry(QtCore.QRect(60, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgCollegeError.setFont(font)
        self.btnDlgCollegeError.setStyleSheet("background: white;\n"
"")
        self.btnDlgCollegeError.setObjectName("btnDlgCollegeError")

        self.retranslateUi(dlgCollegeError)
        QtCore.QMetaObject.connectSlotsByName(dlgCollegeError)

    def retranslateUi(self, dlgCollegeError):
        _translate = QtCore.QCoreApplication.translate
        dlgCollegeError.setWindowTitle(_translate("dlgCollegeError", "Error"))
        self.txtCollegeError.setText(_translate("dlgCollegeError", "All blanks must \n"
" be filled in"))
        self.btnDlgCollegeError.setText(_translate("dlgCollegeError", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgCollegeError = QtWidgets.QDialog()
    ui = Ui_dlgCollegeError()
    ui.setupUi(dlgCollegeError)
    dlgCollegeError.show()
    sys.exit(app.exec_())
