# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgCollegeAdded.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgCollegeAdded(object):
    def setupUi(self, dlgCollegeAdded):
        dlgCollegeAdded.setObjectName("dlgCollegeAdded")
        dlgCollegeAdded.resize(202, 147)
        dlgCollegeAdded.setMinimumSize(QtCore.QSize(202, 147))
        dlgCollegeAdded.setMaximumSize(QtCore.QSize(202, 147))
        dlgCollegeAdded.setStyleSheet("background: #1b2023;\n"
"")
        self.btnDlgCollegeAdded = QtWidgets.QPushButton(dlgCollegeAdded)
        self.btnDlgCollegeAdded.setGeometry(QtCore.QRect(60, 100, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgCollegeAdded.setFont(font)
        self.btnDlgCollegeAdded.setStyleSheet("background: white;\n"
"")
        self.btnDlgCollegeAdded.setObjectName("btnDlgCollegeAdded")
        self.txtCollegeAdded = QtWidgets.QLabel(dlgCollegeAdded)
        self.txtCollegeAdded.setGeometry(QtCore.QRect(30, 10, 151, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtCollegeAdded.setFont(font)
        self.txtCollegeAdded.setStyleSheet("color: #c3bcc2;")
        self.txtCollegeAdded.setObjectName("txtCollegeAdded")

        self.retranslateUi(dlgCollegeAdded)
        QtCore.QMetaObject.connectSlotsByName(dlgCollegeAdded)

    def retranslateUi(self, dlgCollegeAdded):
        _translate = QtCore.QCoreApplication.translate
        dlgCollegeAdded.setWindowTitle(_translate("dlgCollegeAdded", "College Added"))
        self.btnDlgCollegeAdded.setText(_translate("dlgCollegeAdded", "Ok"))
        self.txtCollegeAdded.setText(_translate("dlgCollegeAdded", "College Added"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgCollegeAdded = QtWidgets.QDialog()
    ui = Ui_dlgCollegeAdded()
    ui.setupUi(dlgCollegeAdded)
    dlgCollegeAdded.show()
    sys.exit(app.exec_())
