# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgEditCollege.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgEditCollege(object):
    def setupUi(self, dlgEditCollege):
        dlgEditCollege.setObjectName("dlgEditCollege")
        dlgEditCollege.resize(443, 273)
        dlgEditCollege.setMinimumSize(QtCore.QSize(443, 273))
        dlgEditCollege.setMaximumSize(QtCore.QSize(443, 273))
        dlgEditCollege.setStyleSheet("background: #1b2023;\n"
"color: rgb(195, 188, 194);")
        self.inEditCollegeCode = QtWidgets.QLineEdit(dlgEditCollege)
        self.inEditCollegeCode.setGeometry(QtCore.QRect(20, 60, 231, 31))
        self.inEditCollegeCode.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);\n"
"")
        self.inEditCollegeCode.setText("")
        self.inEditCollegeCode.setObjectName("inEditCollegeCode")
        self.inEditCollegeName = QtWidgets.QLineEdit(dlgEditCollege)
        self.inEditCollegeName.setGeometry(QtCore.QRect(20, 140, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        self.inEditCollegeName.setFont(font)
        self.inEditCollegeName.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);\n"
"")
        self.inEditCollegeName.setText("")
        self.inEditCollegeName.setObjectName("inEditCollegeName")
        self.btnDlgEditCollege = QtWidgets.QPushButton(dlgEditCollege)
        self.btnDlgEditCollege.setGeometry(QtCore.QRect(260, 210, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnDlgEditCollege.setFont(font)
        self.btnDlgEditCollege.setStyleSheet("background-color: gray;\n"
"color: white;\n"
"border: 2px solid rgb(65, 65, 65);\n"
"border-radius: 10px;")
        self.btnDlgEditCollege.setObjectName("btnDlgEditCollege")
        self.bgEditCollege = QtWidgets.QLabel(dlgEditCollege)
        self.bgEditCollege.setGeometry(QtCore.QRect(10, 10, 421, 251))
        self.bgEditCollege.setStyleSheet("background: #2a3133;\n"
"border-radius: 10px;\n"
"border: 2px solid #606364")
        self.bgEditCollege.setText("")
        self.bgEditCollege.setObjectName("bgEditCollege")
        self.txtEditCollegeCode = QtWidgets.QLabel(dlgEditCollege)
        self.txtEditCollegeCode.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditCollegeCode.setFont(font)
        self.txtEditCollegeCode.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditCollegeCode.setObjectName("txtEditCollegeCode")
        self.txtEditCollegeName = QtWidgets.QLabel(dlgEditCollege)
        self.txtEditCollegeName.setGeometry(QtCore.QRect(20, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditCollegeName.setFont(font)
        self.txtEditCollegeName.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditCollegeName.setObjectName("txtEditCollegeName")
        self.bgEditCollege.raise_()
        self.btnDlgEditCollege.raise_()
        self.txtEditCollegeCode.raise_()
        self.txtEditCollegeName.raise_()
        self.inEditCollegeName.raise_()
        self.inEditCollegeCode.raise_()

        self.retranslateUi(dlgEditCollege)
        QtCore.QMetaObject.connectSlotsByName(dlgEditCollege)

    def retranslateUi(self, dlgEditCollege):
        _translate = QtCore.QCoreApplication.translate
        dlgEditCollege.setWindowTitle(_translate("dlgEditCollege", "Edit College"))
        self.btnDlgEditCollege.setText(_translate("dlgEditCollege", "Edit College"))
        self.txtEditCollegeCode.setText(_translate("dlgEditCollege", "Code"))
        self.txtEditCollegeName.setText(_translate("dlgEditCollege", "College Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgEditCollege = QtWidgets.QDialog()
    ui = Ui_dlgEditCollege()
    ui.setupUi(dlgEditCollege)
    dlgEditCollege.show()
    sys.exit(app.exec_())
