# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgEditProgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgEditProgram(object):
    def setupUi(self, dlgEditProgram):
        dlgEditProgram.setObjectName("dlgEditProgram")
        dlgEditProgram.resize(443, 350)
        dlgEditProgram.setMinimumSize(QtCore.QSize(443, 350))
        dlgEditProgram.setMaximumSize(QtCore.QSize(443, 350))
        dlgEditProgram.setStyleSheet("background: #1b2023;\n"
"color: rgb(195, 188, 194);")
        self.inEditProgramCode = QtWidgets.QLineEdit(dlgEditProgram)
        self.inEditProgramCode.setGeometry(QtCore.QRect(20, 60, 231, 31))
        self.inEditProgramCode.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);\n"
"")
        self.inEditProgramCode.setText("")
        self.inEditProgramCode.setObjectName("inEditProgramCode")
        self.inEditProgramName = QtWidgets.QLineEdit(dlgEditProgram)
        self.inEditProgramName.setGeometry(QtCore.QRect(20, 140, 231, 31))
        self.inEditProgramName.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);\n"
"")
        self.inEditProgramName.setText("")
        self.inEditProgramName.setObjectName("inEditProgramName")
        self.btnDlgEditProgram = QtWidgets.QPushButton(dlgEditProgram)
        self.btnDlgEditProgram.setGeometry(QtCore.QRect(260, 280, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnDlgEditProgram.setFont(font)
        self.btnDlgEditProgram.setStyleSheet("background-color: gray;\n"
"color: white;\n"
"border: 2px solid rgb(65, 65, 65);\n"
"border-radius: 10px;")
        self.btnDlgEditProgram.setObjectName("btnDlgEditProgram")
        self.txtEditProgramCode = QtWidgets.QLabel(dlgEditProgram)
        self.txtEditProgramCode.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditProgramCode.setFont(font)
        self.txtEditProgramCode.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditProgramCode.setObjectName("txtEditProgramCode")
        self.txtEditProgramName = QtWidgets.QLabel(dlgEditProgram)
        self.txtEditProgramName.setGeometry(QtCore.QRect(20, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditProgramName.setFont(font)
        self.txtEditProgramName.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditProgramName.setObjectName("txtEditProgramName")
        self.txtEditCollegeCode = QtWidgets.QLabel(dlgEditProgram)
        self.txtEditCollegeCode.setGeometry(QtCore.QRect(20, 180, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditCollegeCode.setFont(font)
        self.txtEditCollegeCode.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditCollegeCode.setObjectName("txtEditCollegeCode")
        self.inEditCollegeCode = QtWidgets.QComboBox(dlgEditProgram)
        self.inEditCollegeCode.setGeometry(QtCore.QRect(20, 220, 111, 31))
        self.inEditCollegeCode.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);")
        self.inEditCollegeCode.setObjectName("inEditCollegeCode")
        self.bgEditProgram = QtWidgets.QLabel(dlgEditProgram)
        self.bgEditProgram.setGeometry(QtCore.QRect(10, 10, 421, 331))
        self.bgEditProgram.setStyleSheet("background: #2a3133;\n"
"border-radius: 10px;\n"
"border: 2px solid #606364")
        self.bgEditProgram.setText("")
        self.bgEditProgram.setObjectName("bgEditProgram")
        self.bgEditProgram.raise_()
        self.btnDlgEditProgram.raise_()
        self.txtEditProgramCode.raise_()
        self.txtEditProgramName.raise_()
        self.txtEditCollegeCode.raise_()
        self.inEditProgramName.raise_()
        self.inEditProgramCode.raise_()
        self.inEditCollegeCode.raise_()

        self.retranslateUi(dlgEditProgram)
        QtCore.QMetaObject.connectSlotsByName(dlgEditProgram)

    def retranslateUi(self, dlgEditProgram):
        _translate = QtCore.QCoreApplication.translate
        dlgEditProgram.setWindowTitle(_translate("dlgEditProgram", "Edit Student"))
        self.btnDlgEditProgram.setText(_translate("dlgEditProgram", "Edit Program"))
        self.txtEditProgramCode.setText(_translate("dlgEditProgram", "Program Code"))
        self.txtEditProgramName.setText(_translate("dlgEditProgram", "Program Name"))
        self.txtEditCollegeCode.setText(_translate("dlgEditProgram", "College Code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgEditProgram = QtWidgets.QDialog()
    ui = Ui_dlgEditProgram()
    ui.setupUi(dlgEditProgram)
    dlgEditProgram.show()
    sys.exit(app.exec_())
