# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgEditStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgEditStudent(object):
    def setupUi(self, dlgEditStudent):
        dlgEditStudent.setObjectName("dlgEditStudent")
        dlgEditStudent.resize(443, 555)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlgEditStudent.sizePolicy().hasHeightForWidth())
        dlgEditStudent.setSizePolicy(sizePolicy)
        dlgEditStudent.setMinimumSize(QtCore.QSize(443, 555))
        dlgEditStudent.setMaximumSize(QtCore.QSize(443, 555))
        font = QtGui.QFont()
        font.setFamily("Inter")
        dlgEditStudent.setFont(font)
        dlgEditStudent.setStyleSheet("background: #1b2023;\n"
"color: rgb(195, 188, 194);")
        self.inEditIDNumber = QtWidgets.QLineEdit(dlgEditStudent)
        self.inEditIDNumber.setGeometry(QtCore.QRect(20, 60, 231, 31))
        self.inEditIDNumber.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);\n"
"")
        self.inEditIDNumber.setText("")
        self.inEditIDNumber.setObjectName("inEditIDNumber")
        self.inEditFirstName = QtWidgets.QLineEdit(dlgEditStudent)
        self.inEditFirstName.setGeometry(QtCore.QRect(20, 140, 231, 31))
        self.inEditFirstName.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);\n"
"")
        self.inEditFirstName.setText("")
        self.inEditFirstName.setObjectName("inEditFirstName")
        self.inEditLastName = QtWidgets.QLineEdit(dlgEditStudent)
        self.inEditLastName.setGeometry(QtCore.QRect(20, 220, 231, 31))
        self.inEditLastName.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);\n"
"")
        self.inEditLastName.setText("")
        self.inEditLastName.setObjectName("inEditLastName")
        self.btnDlgEditStudent = QtWidgets.QPushButton(dlgEditStudent)
        self.btnDlgEditStudent.setGeometry(QtCore.QRect(260, 480, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnDlgEditStudent.setFont(font)
        self.btnDlgEditStudent.setStyleSheet("background-color: gray;\n"
"color: white;\n"
"border: 2px solid rgb(65, 65, 65);\n"
"border-radius: 10px;")
        self.btnDlgEditStudent.setObjectName("btnDlgEditStudent")
        self.bgEditStudent = QtWidgets.QLabel(dlgEditStudent)
        self.bgEditStudent.setGeometry(QtCore.QRect(10, 10, 421, 531))
        self.bgEditStudent.setStyleSheet("background: #2a3133;\n"
"border-radius: 10px;\n"
"border: 2px solid #606364")
        self.bgEditStudent.setText("")
        self.bgEditStudent.setObjectName("bgEditStudent")
        self.txtEditIDNumber = QtWidgets.QLabel(dlgEditStudent)
        self.txtEditIDNumber.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditIDNumber.setFont(font)
        self.txtEditIDNumber.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditIDNumber.setObjectName("txtEditIDNumber")
        self.txtEditFirstName = QtWidgets.QLabel(dlgEditStudent)
        self.txtEditFirstName.setGeometry(QtCore.QRect(20, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditFirstName.setFont(font)
        self.txtEditFirstName.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditFirstName.setObjectName("txtEditFirstName")
        self.txtEditLastName = QtWidgets.QLabel(dlgEditStudent)
        self.txtEditLastName.setGeometry(QtCore.QRect(20, 180, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditLastName.setFont(font)
        self.txtEditLastName.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditLastName.setObjectName("txtEditLastName")
        self.txtEditYearLevel = QtWidgets.QLabel(dlgEditStudent)
        self.txtEditYearLevel.setGeometry(QtCore.QRect(20, 260, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditYearLevel.setFont(font)
        self.txtEditYearLevel.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditYearLevel.setObjectName("txtEditYearLevel")
        self.txtEditGender = QtWidgets.QLabel(dlgEditStudent)
        self.txtEditGender.setGeometry(QtCore.QRect(20, 340, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditGender.setFont(font)
        self.txtEditGender.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditGender.setObjectName("txtEditGender")
        self.txtEditProgramCode = QtWidgets.QLabel(dlgEditStudent)
        self.txtEditProgramCode.setGeometry(QtCore.QRect(20, 410, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtEditProgramCode.setFont(font)
        self.txtEditProgramCode.setStyleSheet("background: #2a3133;\n"
"color: rgb(195, 188, 194);")
        self.txtEditProgramCode.setObjectName("txtEditProgramCode")
        self.inEditGender = QtWidgets.QComboBox(dlgEditStudent)
        self.inEditGender.setGeometry(QtCore.QRect(20, 380, 111, 31))
        self.inEditGender.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);")
        self.inEditGender.setObjectName("inEditGender")
        self.inEditGender.addItem("")
        self.inEditGender.addItem("")
        self.inEditYearLevel = QtWidgets.QComboBox(dlgEditStudent)
        self.inEditYearLevel.setGeometry(QtCore.QRect(20, 300, 111, 31))
        self.inEditYearLevel.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);")
        self.inEditYearLevel.setObjectName("inEditYearLevel")
        self.inEditYearLevel.addItem("")
        self.inEditYearLevel.addItem("")
        self.inEditYearLevel.addItem("")
        self.inEditYearLevel.addItem("")
        self.inEditProgramCode = QtWidgets.QComboBox(dlgEditStudent)
        self.inEditProgramCode.setGeometry(QtCore.QRect(20, 450, 111, 31))
        self.inEditProgramCode.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 2px solid rgb(195, 188, 194);")
        self.inEditProgramCode.setObjectName("inEditProgramCode")
        self.bgEditStudent.raise_()
        self.btnDlgEditStudent.raise_()
        self.txtEditIDNumber.raise_()
        self.txtEditFirstName.raise_()
        self.txtEditLastName.raise_()
        self.txtEditYearLevel.raise_()
        self.txtEditGender.raise_()
        self.txtEditProgramCode.raise_()
        self.inEditFirstName.raise_()
        self.inEditLastName.raise_()
        self.inEditIDNumber.raise_()
        self.inEditGender.raise_()
        self.inEditYearLevel.raise_()
        self.inEditProgramCode.raise_()

        self.retranslateUi(dlgEditStudent)
        QtCore.QMetaObject.connectSlotsByName(dlgEditStudent)

    def retranslateUi(self, dlgEditStudent):
        _translate = QtCore.QCoreApplication.translate
        dlgEditStudent.setWindowTitle(_translate("dlgEditStudent", "Edit Student"))
        self.btnDlgEditStudent.setText(_translate("dlgEditStudent", "Edit Student"))
        self.txtEditIDNumber.setText(_translate("dlgEditStudent", "ID Number"))
        self.txtEditFirstName.setText(_translate("dlgEditStudent", "First Name"))
        self.txtEditLastName.setText(_translate("dlgEditStudent", "Last Name"))
        self.txtEditYearLevel.setText(_translate("dlgEditStudent", "Year Level"))
        self.txtEditGender.setText(_translate("dlgEditStudent", "Gender"))
        self.txtEditProgramCode.setText(_translate("dlgEditStudent", "Program Code"))
        self.inEditGender.setItemText(0, _translate("dlgEditStudent", "Male"))
        self.inEditGender.setItemText(1, _translate("dlgEditStudent", "Female"))
        self.inEditYearLevel.setItemText(0, _translate("dlgEditStudent", "1st Year"))
        self.inEditYearLevel.setItemText(1, _translate("dlgEditStudent", "2nd Year"))
        self.inEditYearLevel.setItemText(2, _translate("dlgEditStudent", "3rd Year"))
        self.inEditYearLevel.setItemText(3, _translate("dlgEditStudent", "4th Year"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgEditStudent = QtWidgets.QDialog()
    ui = Ui_dlgEditStudent()
    ui.setupUi(dlgEditStudent)
    dlgEditStudent.show()
    sys.exit(app.exec_())
