# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgIDNumberError.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgIDNumberError(object):
    def setupUi(self, dlgIDNumberError):
        dlgIDNumberError.setObjectName("dlgIDNumberError")
        dlgIDNumberError.resize(202, 147)
        dlgIDNumberError.setMinimumSize(QtCore.QSize(202, 147))
        dlgIDNumberError.setMaximumSize(QtCore.QSize(202, 147))
        dlgIDNumberError.setStyleSheet("background: #1b2023;")
        self.txtIDNumberFormatError = QtWidgets.QLabel(dlgIDNumberError)
        self.txtIDNumberFormatError.setGeometry(QtCore.QRect(40, 20, 121, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIDNumberFormatError.setFont(font)
        self.txtIDNumberFormatError.setStyleSheet("color: #c3bcc2;")
        self.txtIDNumberFormatError.setObjectName("txtIDNumberFormatError")
        self.btnDlgIDNumberError = QtWidgets.QPushButton(dlgIDNumberError)
        self.btnDlgIDNumberError.setGeometry(QtCore.QRect(60, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgIDNumberError.setFont(font)
        self.btnDlgIDNumberError.setStyleSheet("background: white;\n"
"")
        self.btnDlgIDNumberError.setObjectName("btnDlgIDNumberError")

        self.retranslateUi(dlgIDNumberError)
        QtCore.QMetaObject.connectSlotsByName(dlgIDNumberError)

    def retranslateUi(self, dlgIDNumberError):
        _translate = QtCore.QCoreApplication.translate
        dlgIDNumberError.setWindowTitle(_translate("dlgIDNumberError", "Error"))
        self.txtIDNumberFormatError.setText(_translate("dlgIDNumberError", "Format must be \n"
"   YYYY-NNNN"))
        self.btnDlgIDNumberError.setText(_translate("dlgIDNumberError", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgIDNumberError = QtWidgets.QDialog()
    ui = Ui_dlgIDNumberError()
    ui.setupUi(dlgIDNumberError)
    dlgIDNumberError.show()
    sys.exit(app.exec_())
