# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgIDNumberError2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgIDNumberError2(object):
    def setupUi(self, dlgIDNumberError2):
        dlgIDNumberError2.setObjectName("dlgIDNumberError2")
        dlgIDNumberError2.resize(202, 147)
        dlgIDNumberError2.setMinimumSize(QtCore.QSize(202, 147))
        dlgIDNumberError2.setMaximumSize(QtCore.QSize(202, 147))
        dlgIDNumberError2.setStyleSheet("background: #1b2023;")
        self.txtIDNumberError2 = QtWidgets.QLabel(dlgIDNumberError2)
        self.txtIDNumberError2.setGeometry(QtCore.QRect(40, 20, 121, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIDNumberError2.setFont(font)
        self.txtIDNumberError2.setStyleSheet("color: #c3bcc2;")
        self.txtIDNumberError2.setObjectName("txtIDNumberError2")
        self.btnDlgIDNumberError = QtWidgets.QPushButton(dlgIDNumberError2)
        self.btnDlgIDNumberError.setGeometry(QtCore.QRect(60, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgIDNumberError.setFont(font)
        self.btnDlgIDNumberError.setStyleSheet("background: white;\n"
"")
        self.btnDlgIDNumberError.setObjectName("btnDlgIDNumberError")

        self.retranslateUi(dlgIDNumberError2)
        QtCore.QMetaObject.connectSlotsByName(dlgIDNumberError2)

    def retranslateUi(self, dlgIDNumberError2):
        _translate = QtCore.QCoreApplication.translate
        dlgIDNumberError2.setWindowTitle(_translate("dlgIDNumberError2", "Error"))
        self.txtIDNumberError2.setText(_translate("dlgIDNumberError2", "   ID Number \n"
" already exists"))
        self.btnDlgIDNumberError.setText(_translate("dlgIDNumberError2", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgIDNumberError2 = QtWidgets.QDialog()
    ui = Ui_dlgIDNumberError2()
    ui.setupUi(dlgIDNumberError2)
    dlgIDNumberError2.show()
    sys.exit(app.exec_())
