# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgProgramError3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgProgramError3(object):
    def setupUi(self, dlgProgramError3):
        dlgProgramError3.setObjectName("dlgProgramError3")
        dlgProgramError3.resize(202, 147)
        dlgProgramError3.setMinimumSize(QtCore.QSize(202, 147))
        dlgProgramError3.setMaximumSize(QtCore.QSize(202, 147))
        dlgProgramError3.setStyleSheet("background: #1b2023;")
        self.txtProgramError3 = QtWidgets.QLabel(dlgProgramError3)
        self.txtProgramError3.setGeometry(QtCore.QRect(40, 20, 131, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtProgramError3.setFont(font)
        self.txtProgramError3.setStyleSheet("color: #c3bcc2;")
        self.txtProgramError3.setObjectName("txtProgramError3")
        self.btnDlgProgramError3 = QtWidgets.QPushButton(dlgProgramError3)
        self.btnDlgProgramError3.setGeometry(QtCore.QRect(60, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgProgramError3.setFont(font)
        self.btnDlgProgramError3.setStyleSheet("background: white;\n"
"")
        self.btnDlgProgramError3.setObjectName("btnDlgProgramError3")

        self.retranslateUi(dlgProgramError3)
        QtCore.QMetaObject.connectSlotsByName(dlgProgramError3)

    def retranslateUi(self, dlgProgramError3):
        _translate = QtCore.QCoreApplication.translate
        dlgProgramError3.setWindowTitle(_translate("dlgProgramError3", "Error"))
        self.txtProgramError3.setText(_translate("dlgProgramError3", "  Program Name \n"
" already exists"))
        self.btnDlgProgramError3.setText(_translate("dlgProgramError3", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgProgramError3 = QtWidgets.QDialog()
    ui = Ui_dlgProgramError3()
    ui.setupUi(dlgProgramError3)
    dlgProgramError3.show()
    sys.exit(app.exec_())
