# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgProgramError.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgProgramError(object):
    def setupUi(self, dlgProgramError):
        dlgProgramError.setObjectName("dlgProgramError")
        dlgProgramError.resize(202, 147)
        dlgProgramError.setMinimumSize(QtCore.QSize(202, 147))
        dlgProgramError.setMaximumSize(QtCore.QSize(202, 147))
        dlgProgramError.setStyleSheet("background: #1b2023;")
        self.txtProgramError = QtWidgets.QLabel(dlgProgramError)
        self.txtProgramError.setGeometry(QtCore.QRect(40, 20, 131, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtProgramError.setFont(font)
        self.txtProgramError.setStyleSheet("color: #c3bcc2;")
        self.txtProgramError.setObjectName("txtProgramError")
        self.btnDlgProgramError = QtWidgets.QPushButton(dlgProgramError)
        self.btnDlgProgramError.setGeometry(QtCore.QRect(60, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgProgramError.setFont(font)
        self.btnDlgProgramError.setStyleSheet("background: white;\n"
"")
        self.btnDlgProgramError.setObjectName("btnDlgProgramError")

        self.retranslateUi(dlgProgramError)
        QtCore.QMetaObject.connectSlotsByName(dlgProgramError)

    def retranslateUi(self, dlgProgramError):
        _translate = QtCore.QCoreApplication.translate
        dlgProgramError.setWindowTitle(_translate("dlgProgramError", "Error"))
        self.txtProgramError.setText(_translate("dlgProgramError", "All blanks must \n"
" be filled in"))
        self.btnDlgProgramError.setText(_translate("dlgProgramError", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgProgramError = QtWidgets.QDialog()
    ui = Ui_dlgProgramError()
    ui.setupUi(dlgProgramError)
    dlgProgramError.show()
    sys.exit(app.exec_())
