# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgProgramAdded.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgProgramAdded(object):
    def setupUi(self, dlgProgramAdded):
        dlgProgramAdded.setObjectName("dlgProgramAdded")
        dlgProgramAdded.resize(202, 147)
        dlgProgramAdded.setMinimumSize(QtCore.QSize(202, 147))
        dlgProgramAdded.setMaximumSize(QtCore.QSize(202, 147))
        dlgProgramAdded.setStyleSheet("background: #1b2023;")
        self.txtProgramAdded = QtWidgets.QLabel(dlgProgramAdded)
        self.txtProgramAdded.setGeometry(QtCore.QRect(30, 10, 151, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtProgramAdded.setFont(font)
        self.txtProgramAdded.setStyleSheet("color: #c3bcc2;")
        self.txtProgramAdded.setObjectName("txtProgramAdded")
        self.btnDlgProgramAdded = QtWidgets.QPushButton(dlgProgramAdded)
        self.btnDlgProgramAdded.setGeometry(QtCore.QRect(60, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgProgramAdded.setFont(font)
        self.btnDlgProgramAdded.setStyleSheet("background: white;\n"
"")
        self.btnDlgProgramAdded.setObjectName("btnDlgProgramAdded")

        self.retranslateUi(dlgProgramAdded)
        QtCore.QMetaObject.connectSlotsByName(dlgProgramAdded)

    def retranslateUi(self, dlgProgramAdded):
        _translate = QtCore.QCoreApplication.translate
        dlgProgramAdded.setWindowTitle(_translate("dlgProgramAdded", "Program Added"))
        self.txtProgramAdded.setText(_translate("dlgProgramAdded", "Program Added"))
        self.btnDlgProgramAdded.setText(_translate("dlgProgramAdded", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgProgramAdded = QtWidgets.QDialog()
    ui = Ui_dlgProgramAdded()
    ui.setupUi(dlgProgramAdded)
    dlgProgramAdded.show()
    sys.exit(app.exec_())
