# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgProgramUpdated.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgProgramUpdated(object):
    def setupUi(self, dlgProgramUpdated):
        dlgProgramUpdated.setObjectName("dlgProgramUpdated")
        dlgProgramUpdated.resize(202, 147)
        dlgProgramUpdated.setMinimumSize(QtCore.QSize(202, 147))
        dlgProgramUpdated.setMaximumSize(QtCore.QSize(202, 147))
        dlgProgramUpdated.setStyleSheet("background: #1b2023;")
        self.btnProgramUpdated = QtWidgets.QPushButton(dlgProgramUpdated)
        self.btnProgramUpdated.setGeometry(QtCore.QRect(60, 100, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnProgramUpdated.setFont(font)
        self.btnProgramUpdated.setStyleSheet("background: white;\n"
"")
        self.btnProgramUpdated.setObjectName("btnProgramUpdated")
        self.txtStudentAdded = QtWidgets.QLabel(dlgProgramUpdated)
        self.txtStudentAdded.setGeometry(QtCore.QRect(20, 10, 171, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtStudentAdded.setFont(font)
        self.txtStudentAdded.setStyleSheet("color: #c3bcc2;")
        self.txtStudentAdded.setObjectName("txtStudentAdded")

        self.retranslateUi(dlgProgramUpdated)
        QtCore.QMetaObject.connectSlotsByName(dlgProgramUpdated)

    def retranslateUi(self, dlgProgramUpdated):
        _translate = QtCore.QCoreApplication.translate
        dlgProgramUpdated.setWindowTitle(_translate("dlgProgramUpdated", "Student Added"))
        self.btnProgramUpdated.setText(_translate("dlgProgramUpdated", "Ok"))
        self.txtStudentAdded.setText(_translate("dlgProgramUpdated", "Program Updated"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgProgramUpdated = QtWidgets.QDialog()
    ui = Ui_dlgProgramUpdated()
    ui.setupUi(dlgProgramUpdated)
    dlgProgramUpdated.show()
    sys.exit(app.exec_())
