# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgProgramError2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgProgramError2(object):
    def setupUi(self, dlgProgramError2):
        dlgProgramError2.setObjectName("dlgProgramError2")
        dlgProgramError2.resize(202, 147)
        dlgProgramError2.setMinimumSize(QtCore.QSize(202, 147))
        dlgProgramError2.setMaximumSize(QtCore.QSize(202, 147))
        dlgProgramError2.setStyleSheet("background: #1b2023;")
        self.txtProgramError2 = QtWidgets.QLabel(dlgProgramError2)
        self.txtProgramError2.setGeometry(QtCore.QRect(40, 20, 131, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtProgramError2.setFont(font)
        self.txtProgramError2.setStyleSheet("color: #c3bcc2;")
        self.txtProgramError2.setObjectName("txtProgramError2")
        self.btnDlgProgramError2 = QtWidgets.QPushButton(dlgProgramError2)
        self.btnDlgProgramError2.setGeometry(QtCore.QRect(60, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgProgramError2.setFont(font)
        self.btnDlgProgramError2.setStyleSheet("background: white;\n"
"")
        self.btnDlgProgramError2.setObjectName("btnDlgProgramError2")

        self.retranslateUi(dlgProgramError2)
        QtCore.QMetaObject.connectSlotsByName(dlgProgramError2)

    def retranslateUi(self, dlgProgramError2):
        _translate = QtCore.QCoreApplication.translate
        dlgProgramError2.setWindowTitle(_translate("dlgProgramError2", "Error"))
        self.txtProgramError2.setText(_translate("dlgProgramError2", "  Program Code \n"
" already exists"))
        self.btnDlgProgramError2.setText(_translate("dlgProgramError2", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgProgramError2 = QtWidgets.QDialog()
    ui = Ui_dlgProgramError2()
    ui.setupUi(dlgProgramError2)
    dlgProgramError2.show()
    sys.exit(app.exec_())
