# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgStudentAdded.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgStudentAdded(object):
    def setupUi(self, dlgStudentAdded):
        dlgStudentAdded.setObjectName("dlgStudentAdded")
        dlgStudentAdded.resize(202, 147)
        dlgStudentAdded.setMinimumSize(QtCore.QSize(202, 147))
        dlgStudentAdded.setMaximumSize(QtCore.QSize(202, 147))
        dlgStudentAdded.setStyleSheet("background: #1b2023;")
        self.btnDlgStudentAdded = QtWidgets.QPushButton(dlgStudentAdded)
        self.btnDlgStudentAdded.setGeometry(QtCore.QRect(60, 100, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgStudentAdded.setFont(font)
        self.btnDlgStudentAdded.setStyleSheet("background: white;\n"
"")
        self.btnDlgStudentAdded.setObjectName("btnDlgStudentAdded")
        self.txtStudentAdded = QtWidgets.QLabel(dlgStudentAdded)
        self.txtStudentAdded.setGeometry(QtCore.QRect(30, 10, 151, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtStudentAdded.setFont(font)
        self.txtStudentAdded.setStyleSheet("color: #c3bcc2;")
        self.txtStudentAdded.setObjectName("txtStudentAdded")

        self.retranslateUi(dlgStudentAdded)
        QtCore.QMetaObject.connectSlotsByName(dlgStudentAdded)

    def retranslateUi(self, dlgStudentAdded):
        _translate = QtCore.QCoreApplication.translate
        dlgStudentAdded.setWindowTitle(_translate("dlgStudentAdded", "Student Added"))
        self.btnDlgStudentAdded.setText(_translate("dlgStudentAdded", "Ok"))
        self.txtStudentAdded.setText(_translate("dlgStudentAdded", "Student Added"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgStudentAdded = QtWidgets.QDialog()
    ui = Ui_dlgStudentAdded()
    ui.setupUi(dlgStudentAdded)
    dlgStudentAdded.show()
    sys.exit(app.exec_())
