# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgStudentDeleted.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgStudentDeleted(object):
    def setupUi(self, dlgStudentDeleted):
        dlgStudentDeleted.setObjectName("dlgStudentDeleted")
        dlgStudentDeleted.resize(202, 147)
        dlgStudentDeleted.setMinimumSize(QtCore.QSize(202, 147))
        dlgStudentDeleted.setMaximumSize(QtCore.QSize(202, 147))
        dlgStudentDeleted.setStyleSheet("background: #1b2023;")
        self.txtStudentDeleted = QtWidgets.QLabel(dlgStudentDeleted)
        self.txtStudentDeleted.setGeometry(QtCore.QRect(20, 10, 181, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtStudentDeleted.setFont(font)
        self.txtStudentDeleted.setStyleSheet("color: #c3bcc2;")
        self.txtStudentDeleted.setObjectName("txtStudentDeleted")
        self.btnDlgstudentDeleted = QtWidgets.QPushButton(dlgStudentDeleted)
        self.btnDlgstudentDeleted.setGeometry(QtCore.QRect(60, 100, 75, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.btnDlgstudentDeleted.setFont(font)
        self.btnDlgstudentDeleted.setStyleSheet("background: white;\n"
"")
        self.btnDlgstudentDeleted.setObjectName("btnDlgstudentDeleted")

        self.retranslateUi(dlgStudentDeleted)
        QtCore.QMetaObject.connectSlotsByName(dlgStudentDeleted)

    def retranslateUi(self, dlgStudentDeleted):
        _translate = QtCore.QCoreApplication.translate
        dlgStudentDeleted.setWindowTitle(_translate("dlgStudentDeleted", "Student Deleted"))
        self.txtStudentDeleted.setText(_translate("dlgStudentDeleted", "Student Deleted"))
        self.btnDlgstudentDeleted.setText(_translate("dlgStudentDeleted", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgStudentDeleted = QtWidgets.QDialog()
    ui = Ui_dlgStudentDeleted()
    ui.setupUi(dlgStudentDeleted)
    dlgStudentDeleted.show()
    sys.exit(app.exec_())
